name: Seafile Server Build CI

on: push

jobs:
  test_build:
    runs-on: ubuntu-latest
    # container:
    #     image: mariadb:latest
    #     env:
    #         MARIADB_USER: root
    #         MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
    #         MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
    #     ports:
    #       - 3306

    steps:
        - name: install packages
          run: |
            sudo apt-get install -y ssh libevent-dev libcurl4-openssl-dev libglib2.0-dev uuid-dev intltool 
            sudo apt-get install -y libsqlite3-dev libmysqlclient-dev libarchive-dev libtool libjansson-dev valac libfuse-dev
            sudo apt-get install -y cmake re2c flex sqlite3 python-pip git libssl-dev libldap2-dev libonig-dev vim vim-scripts
            sudo apt-get install -y wget cmake gcc autoconf automake mysql-client librados-dev libxml2-dev curl telnet
            sudo apt-get install -y netcat unzip netbase ca-certificates apt-transport-https build-essential libxslt1-dev libffi-dev
            sudo apt-get install -y libpcre3-dev zlib1g-dev xz-utils nginx pkg-config poppler-utils libmemcached-dev
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            apt-get install -y nodejs

        - name: install python
          uses: actions/setup-python@v4
          with:
            python-version: "3.8"
        
        - name: clone dependencies in a given dir
          run: |
            cd ~/
            mkdir -p ~/dev/source-code
            cd ~/dev/source-code
            
            git clone https://github.com/haiwen/libevhtp.git
            git clone https://github.com/haiwen/libsearpc.git
            git clone https://github.com/haiwen/seafile-server.git

        - name: compile libevhtp
          run: |
            cd libevhtp
            cmake -DEVHTP_DISABLE_SSL=ON -DEVHTP_BUILD_SHARED=OFF .
            make
            make install
            ldconfig
        
        - name: compile libsearpc
          run: |
            cd ../libsearpc
            ./autogen.sh
            ./configure
            make
            make install
            ldconfig

        - name: compile seafile-server
          run: |
            cd ../seafile-server
            ./autogen.sh
            ./configure --disable-fuse
            make
            make install
            ldconfig

        # - name: checkout
        #   uses: actions/checkout@v3

        
        # - name: install dependencies and test
        #   run: |
        #     cd $GITHUB_WORKSPACE
        #     ./ci/install-deps.sh
        #     ./ci/run.py
